version: "2.1"

services:
    duplicati:
        image: lscr.io/linuxserver/duplicati:2.0.6
        restart: unless-stopped
        container_name: duplicati
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Zurich
        volumes:
            - config:/config
            - backups:/backups
            - source:/source

volumes:
    config:
    backups:
    source:
