version: "3.3"

services:
    ghost_app:
        image: ghost:5.42.0
        container_name: ghost_app
        restart: unless-stopped
        depends_on:
            - ghost_db
        networks:
            - aquahubstudio
            - ghost
        volumes:
            - ghost_data:/var/lib/ghost
        environment:
            - database__client=mysql
            - database__connection__host=ghost_db
            - database__connection__user=root
            - database__connection__password=ghost
            - database__connection__database=ghost

    ghost_db:
        image: mysql:8.0
        container_name: ghost_db
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=ghost
        networks:
            - ghost
        volumes:
            - sql_data:/var/lib/mysql

networks:
    aquahubstudio:
        external: true
    ghost:

volumes:
    ghost_data:
    sql_data:
