version: "3.3"

services:
    ghost:
        image: bitnami/ghost:5.39.0
        container_name: ghost
        restart: unless-stopped
        depends_on:
            - ghost_db
        networks:
            - aquahubstudio
            - ghost
        volumes:
            - data:/bitnami/ghost
        environment:
            - url=https://blog.aquahub.studio
            - GHOST_HOST=https://blog.aquahub.studio
            - GHOST_DATABASE_HOST=ghost_db
            - GHOST_DATABASE_USER=root
            - GHOST_DATABASE_PASSWORD=${GHOST_DB_ROOT_PASSWORD}
            - GHOST_DATABASE_NAME=ghost
            - GHOST_DATABASE_PORT_NUMBER=3306

    ghost_db:
        image: mariadb:10.9.5
        container_name: ghost_db
        restart: unless-stopped
        environment:
            - MARIADB_DATABASE=ghost
            - MARIADB_ROOT_USER=root
            - MARIADB_ROOT_PASSWORD=${GHOST_DB_ROOT_PASSWORD}
        networks:
            - ghost
        volumes:
            - db:/bitnami/mariadb

networks:
    aquahubstudio:
        external: true
    ghost:

volumes:
    data:
    db:
