version: "3.3"

services:
    ghost_app:
        image: ghost:5.42.0
        container_name: ghost_app
        restart: unless-stopped
        depends_on:
            - ghost_db
        networks:
            - aquahubstudio
            - ghost
        volumes:
            - data:/var/lib/ghost
        environment:
            - database__client=mysql
            - database__connection__host=ghost_db
            - database__connection__user=root
            - database__connection__password=ghost
            - database__connection__database=ghost

    ghost_db:
        image: mysql:5.7.41
        container_name: ghost_db
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=ghost
            - MYSQL_DATABASE=ghost
        networks:
            - ghost
        volumes:
            - db:/var/lib/mysql

networks:
    aquahubstudio:
        external: true
    ghost:

volumes:
    data:
    db:
